### PR TITLE
add definition of pipeline

### PR DESCRIPTION
**Pull request by mollyyoung**
cc @comharris

### CODE REVIEW

**Comment by mollyyoung** [comment]
@comharris  I am unable to assign this, could you assist?

**Comment by comharris** [comment]
> @comharris I am unable to assign this, could you assist?

@mollyyoung I unfortunately don't have the rights to merge anything into this (I think it's just Ian, but not 100%)

**Comment by mollyyoung** [comment]
No worries, thank you @comharris.

**Comment by it33** [comment]
@mollyyoung merged

**Pull request merged**
